[package]
name = "proof_verifier"
type = "contract"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v1.1.2", directory = "noir-projects/aztec-nr/aztec" }
bb_proof_verification = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v1.1.2", directory = "barretenberg/noir/bb_proof_verification" }
